bookingApp:
    ASPNETCORE_ENVIRONMENT:
      _default: "DevStand"
      dev: "DevStand"
      prod: "Production"
    DB_HOST: 
      _default: "postgres"
      dev: "DevStand"
      prod: "127.0.0.1"
    DB_USER: 
      _default: postgres
    DB_PASSWORD: 
      _default: postgres
      prod: "pass"
    DB_NAME: 
      _default: "postgres"
    DB_PORT: 
      _default: "postgres"
    APP_PORT: 
      _default: "9002"
      dev: "9002"
      prod: "8080"


bookingAppDeploy:
  replicaCount: 1
  image:
    repository: aliakseizhurauliou/booking-app
    pullPolicy: IfNotPresent
    tag: "latest"
  resources:
    limits:
      memory: "256Mi"
      cpu: "500m"


persistenceVolume:
  storageClassName: ""
  storage: "2Gi"
  accessModes: ["ReadWriteMany"]
  hostPath: "/data/postgresql"


ingress:
  enabled: true
  className: "nginx"
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: booking.appka.com
      paths:
        - path: /
          pathType: ImplementationSpecific