apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.postgresService.name }}
spec:
  selector:
    app: {{ .Values.postgresDeployment.selector }}
  ports:
  - port: {{ .Values.postgresDeployment.port }}
    targetPort: {{ .Values.postgresDeployment.port }}
