---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Chart.Name }}
spec:
  storageClassName: {{ .Values.persistenceVolume.storageClassName }}
  capacity:
    storage: {{ .Values.persistenceVolume.storage }}
  accessModes:
    {{ .Values.persistenceVolume.accessModes }}
  hostPath:
    path: {{ .Values.persistenceVolume.hostPath }}