apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-volume-claim
spec:
  storageClassName: {{ .Values.persistenceVolume.storageClassName }}
  accessModes: {{ .Values.persistenceVolume.accessModes }}
  resources:
    requests:
      storage: {{ .Values.persistenceVolume.storage }}