---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-svc
spec:
  type: ClusterIP
  selector:
    app: {{ .Chart.Name }}
  ports:
  - port: {{ .Values.bookingApp.APP_PORT._default }}
    targetPort: {{  .Values.bookingApp.APP_PORT._default }}